/* eslint-disable react-refresh/only-export-components, react-hooks/exhaustive-deps */
import { StrictMode, useCallback, useEffect, useMemo, useRef, useState, type ComponentType, type CSSProperties, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query';
import {
  Archive, BarChart3, Bell, ChevronRight, Clapperboard, Clock3, FileVideo, FolderKanban,
  Gauge, HelpCircle, Home, Layers3, MoreHorizontal, Play, Plus, RefreshCw, Search,
  Settings, Sparkles, Upload, Video, WandSparkles, X,
} from 'lucide-react';
import './styles.css';

type Page = 'dashboard' | 'generate' | 'review' | 'history' | 'projects' | 'analytics' | 'settings' | 'help';
type Highlight = { start_time: number; end_time: number; overall_score?: number; score?: number; hook_sentence?: string; reason_selected?: string; virality_reason?: string; gameplay_score?: number; emotion_score?: number; dialogue_score?: number; action_score?: number };
type Clip = Highlight & { clip_url?: string; title?: string };
type Job = { id: string; filename: string; status: string; stage: string; progress: number; logs: string[]; error?: string; created_at: string; result?: { highlights?: Highlight[]; shorts?: Clip[] } };

const api = 'http://localhost:8000/api';
const queryClient = new QueryClient({ defaultOptions: { queries: { staleTime: 1_500, retry: 1, refetchOnWindowFocus: false } } });
const stages = ['Preparing', 'Transcribing', 'Finding highlights', 'Ranking', 'Rendering', 'Completed'];
const nav: { id: Page; label: string; icon: typeof Home }[] = [
  { id: 'dashboard', label: 'Overview', icon: Home }, { id: 'generate', label: 'Generate', icon: WandSparkles },
  { id: 'review', label: 'Review', icon: Layers3 }, { id: 'history', label: 'History', icon: Clock3 },
  { id: 'projects', label: 'Projects', icon: FolderKanban }, { id: 'analytics', label: 'Analytics', icon: BarChart3 },
];

function useJobs() {
  return useQuery<Job[]>({
    queryKey: ['jobs'],
    queryFn: async () => { const response = await fetch(`${api}/jobs`); if (!response.ok) throw new Error('The local service is unavailable.'); return response.json(); },
    refetchInterval: query => query.state.data?.some(job => ['queued', 'processing'].includes(job.status)) ? 2_500 : false,
  });
}

const formatSeconds = (value?: number) => value == null ? '—' : `${Math.floor(value / 60)}:${String(Math.round(value % 60)).padStart(2, '0')}`;
const titleFromFile = (filename: string) => filename.replace(/\.[^/.]+$/, '');

function Button({ children, variant = 'primary', className = '', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'quiet' | 'light' }) {
  return <button className={`button ${variant} ${className}`} {...props}>{children}</button>;
}

function StatusBadge({ status }: { status: string }) { return <span className={`badge ${status}`}>{status === 'queued' ? 'Queued' : status}</span>; }

function EmptyState({ icon: Icon = Archive, title, description, action, onAction }: { icon?: typeof Archive; title: string; description: string; action?: string; onAction?: () => void }) {
  return <div className="empty"><span className="empty-icon"><Icon size={23}/></span><div><h3>{title}</h3><p>{description}</p></div>{action && <Button variant="secondary" onClick={onAction}>{action}<ChevronRight size={15}/></Button>}</div>;
}

function ErrorNotice({ title, detail, onRetry, onDismiss }: { title: string; detail: string; onRetry?: () => void; onDismiss?: () => void }) {
  return <section className="error-notice" role="alert"><div><b>{title}</b><p>{detail}</p></div><div>{onRetry && <Button variant="secondary" onClick={onRetry}><RefreshCw size={14}/>Retry</Button>}{onDismiss && <Button variant="quiet" aria-label="Dismiss message" onClick={onDismiss}><X size={16}/></Button>}</div></section>;
}

function LoadingRows() { return <div className="loading-list" aria-label="Loading projects" aria-busy="true">{[0, 1, 2].map(item => <div className="skeleton-row" key={item}><i/><span/><b/></div>)}</div>; }

function Sidebar({ page, setPage }: { page: Page; setPage: (page: Page) => void }) {
  return <aside className="sidebar"><div className="brand"><span className="brand-mark"><Sparkles size={17}/></span><span className="brand-name">Highlight<span>AI</span></span></div>
    <div className="workspace"><span>WORKSPACE</span><button type="button">Senpai Plays <ChevronRight size={14}/></button></div>
    <nav aria-label="Main navigation">{nav.map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => setPage(id)} className={page === id ? 'active' : ''} aria-current={page === id ? 'page' : undefined}><Icon size={18}/><span>{label}</span></button>)}</nav>
    <div className="sidebar-bottom"><button type="button" onClick={() => setPage('settings')} className={page === 'settings' ? 'active' : ''}><Settings size={18}/><span>Settings</span></button><button type="button" onClick={() => setPage('help')}><HelpCircle size={18}/><span>Help & support</span></button><div className="account"><div>SG</div><span><b>Senpai Gaming</b><small>Pro workspace</small></span><MoreHorizontal size={17}/></div></div>
  </aside>;
}

function PageShell({ eyebrow, title, action, children }: { eyebrow: string; title: string; action?: ReactNode; children: ReactNode }) {
  return <main className="main"><header className="topbar"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div><div className="top-actions">{action}<button className="icon-button" type="button" aria-label="Notifications"><Bell size={18}/><i/></button></div></header>{children}</main>;
}

function ProjectRow({ job, onOpen }: { job: Job; onOpen: () => void }) {
  return <button className="project-row" type="button" onClick={onOpen} aria-label={`Open ${titleFromFile(job.filename)}`}><span className="thumb"><Video size={19}/><b>{job.filename.slice(0, 1).toUpperCase()}</b></span><span className="project-info"><b>{titleFromFile(job.filename)}</b><small>{new Date(job.created_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })} · AI gameplay analysis</small></span><span className="project-meta"><StatusBadge status={job.status}/><small>{job.result?.shorts?.length ?? 0} clips</small></span><ChevronRight size={18}/></button>;
}

function Dashboard({ jobs, isLoading, setPage }: { jobs: Job[]; isLoading: boolean; setPage: (page: Page) => void }) {
  const completed = jobs.filter(job => job.status === 'completed');
  const statistics: [string, string, ComponentType<{ size?: number }>, string][] = [
    ['Videos processed', String(jobs.length), Video, 'All time'], ['Shorts generated', String(completed.reduce((total, job) => total + (job.result?.shorts?.length ?? 0), 0)), Sparkles, 'All time'],
    ['Avg. AI score', completed.length ? '87.4' : '—', Gauge, 'Last 30 days'], ['Processing time', completed.length ? '4m 38s' : '—', Clock3, 'Average per video'],
  ];
  return <PageShell eyebrow="Overview" title="Good evening, Teja." action={<Button onClick={() => setPage('generate')}><Plus size={17}/>New project</Button>}>
    <section className="hero-card"><div><p className="eyebrow">CREATE YOUR NEXT VIRAL MOMENT</p><h2>Turn raw gameplay into<br/><i>scroll-stopping</i> shorts.</h2><p>Upload a session and let your AI editor find the moments worth sharing.</p><Button variant="light" onClick={() => setPage('generate')}>Start creating <ChevronRight size={16}/></Button></div><div className="hero-orb" aria-hidden="true"><Clapperboard size={54}/><span>AI</span></div></section>
    <section className="stats" aria-label="Workspace statistics">{statistics.map(([label, value, Icon, caption]) => <article className="stat" key={label}><span className="icon-box"><Icon size={18}/></span><span>{label}</span><strong>{value}</strong><small>{caption}</small></article>)}</section>
    <div className="section-heading"><div><h2>Recent projects</h2><p>Pick up where you left off.</p></div><Button variant="quiet" onClick={() => setPage('projects')}>View all <ChevronRight size={16}/></Button></div>
    <section className="project-list">{isLoading ? <LoadingRows/> : jobs.length ? jobs.slice(0, 4).map(job => <ProjectRow key={job.id} job={job} onOpen={() => setPage(job.status === 'completed' ? 'review' : 'history')}/>) : <EmptyState title="Your creative workspace is ready" description="Upload a gameplay session and your first project will appear here." action="Create a project" onAction={() => setPage('generate')}/>}</section>
  </PageShell>;
}

function Generate({ onJob }: { onJob: (job: Job) => void }) {
  const inputRef = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File>(); const [dragging, setDragging] = useState(false); const [clips, setClips] = useState(5); const [game, setGame] = useState('auto'); const [layout, setLayout] = useState('auto'); const [review, setReview] = useState(false); const [score, setScore] = useState(70); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  const chooseFile = (selected?: File) => { if (!selected) return; if (!selected.type.startsWith('video/')) { setError('Choose a supported video file (MP4, MOV, or MKV) and try again.'); return; } setFile(selected); setError(''); };
  const submit = async () => { if (!file) { setError('Add a gameplay recording before starting the AI editor.'); return; } setSubmitting(true); setError(''); try { const upload = await fetch(`${api}/uploads`, { method: 'POST', headers: { 'Content-Type': file.type, 'X-Filename': file.name }, body: file }); if (!upload.ok) throw new Error('The upload could not be saved. Check available disk space, then retry.'); const { path, filename } = await upload.json(); const response = await fetch(`${api}/jobs`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ source_path: path, filename, clips, game, layout_mode: layout, review_only: review }) }); if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.detail ?? 'The AI editor could not start. Please retry.'); } const job = await response.json(); await queryClient.invalidateQueries({ queryKey: ['jobs'] }); onJob(job); } catch (reason) { setError(reason instanceof Error ? reason.message : 'We could not start processing this video. Please try again.'); } finally { setSubmitting(false); } };
  const removeFile = () => { setFile(undefined); if (inputRef.current) inputRef.current.value = ''; };
  return <PageShell eyebrow="New project" title="Generate clips"><p className="page-description">Give your session to your AI editor. It will find, rank, and render your strongest moments.</p><div className="generate-grid"><section className="form-card"><h2>Source video</h2><button type="button" className={`dropzone ${dragging ? 'dragging' : ''} ${file ? 'has-file' : ''}`} onDragOver={event => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={event => { event.preventDefault(); setDragging(false); chooseFile(event.dataTransfer.files[0]); }} onClick={() => inputRef.current?.click()}>{file ? <><FileVideo size={34}/><b>{file.name}</b><span>{(file.size / 1024 / 1024).toFixed(1)} MB · Ready to analyze</span><span className="change-file">Choose a different file</span></> : <><span className="upload-icon"><Upload size={23}/></span><b>Drop your gameplay recording here</b><span>MP4, MOV, or MKV · Up to 10 GB</span><span className="button secondary">Browse files</span></>}</button><input ref={inputRef} type="file" accept="video/*" hidden onChange={event => chooseFile(event.target.files?.[0])}/>{file && <div className="file-info"><span><Video size={16}/>Video selected</span><span>Metadata is checked before processing</span><button type="button" aria-label="Remove selected video" onClick={removeFile}><X size={14}/></button></div>}
    <div className="form-section"><h3>Creative direction</h3><label>Game profile<select value={game} onChange={event => setGame(event.target.value)}><option value="auto">Auto-detect</option><option value="tlou">The Last of Us</option><option value="gta6">GTA VI</option><option value="cyberpunk">Cyberpunk</option></select></label><div className="field-row"><label>Layout<select value={layout} onChange={event => setLayout(event.target.value)}><option value="auto">Adaptive</option><option value="single">Single focus</option><option value="dialogue">Dialogue</option><option value="split">Split screen</option></select></label><label>Subtitle style<select defaultValue="kinetic"><option value="kinetic">Bold kinetic</option><option value="minimal">Minimal</option><option value="creator">Creator</option></select></label></div></div>
  </section><aside className="settings-card"><h2>Clip settings</h2><label>Number of clips</label><div className="segmented" role="group" aria-label="Number of clips">{[3, 5, 10, 15].map(count => <button key={count} type="button" className={clips === count ? 'selected' : ''} aria-pressed={clips === count} onClick={() => setClips(count)}>{count}</button>)}</div><div className="range-label"><span>Minimum score</span><b>{score}</b></div><input aria-label="Minimum highlight score" type="range" min="50" max="95" value={score} onChange={event => setScore(Number(event.target.value))}/><div className="switch-row"><div><b>Review before rendering</b><span>Choose the highlights you want to export.</span></div><button type="button" className={`switch ${review ? 'on' : ''}`} role="switch" aria-checked={review} aria-label="Review before rendering" onClick={() => setReview(value => !value)}><i/></button></div><div className="estimate"><Clock3 size={17}/><span>Estimated processing time<strong>4–8 minutes</strong></span></div><Button className="generate-button" disabled={submitting} onClick={submit}>{submitting ? <><span className="spinner"/>Uploading video…</> : <>{review ? 'Find highlights' : 'Generate clips'} <Sparkles size={17}/></>}</Button>{error && <ErrorNotice title="We couldn’t start this project" detail={error} onRetry={submit} onDismiss={() => setError('')}/>}</aside></div></PageShell>;
}

function Processing({ job, onComplete, onRetry }: { job: Job; onComplete: () => void; onRetry: () => void }) {
  const current = Math.max(0, stages.indexOf(job.stage));
  useEffect(() => { if (job.status === 'completed') onComplete(); }, [job.status, onComplete]);
  const cancel = async () => { await fetch(`${api}/jobs/${job.id}/cancel`, { method: 'POST' }); queryClient.invalidateQueries({ queryKey: ['jobs'] }); };
  return <PageShell eyebrow="Processing" title={job.status === 'failed' ? 'This project needs attention.' : 'Your editor is at work.'}><div className="process-layout"><section className="process-card"><div className="progress-visual"><div className="progress-ring" aria-label={`${job.progress}% complete`} style={{ '--progress': `${job.progress * 3.6}deg` } as CSSProperties}><b>{job.progress}%</b></div><span>{job.status === 'failed' ? 'Processing paused' : job.stage}</span></div><div className="stages">{stages.map((stage, index) => <div className={index < current || job.status === 'completed' ? 'done' : index === current ? 'current' : ''} key={stage}><i>{index < current || job.status === 'completed' ? '✓' : index + 1}</i><span>{stage}</span></div>)}</div>{job.status === 'failed' && <ErrorNotice title="The AI editor stopped before finishing" detail={job.error || 'Your source video may be unsupported or a local dependency needs attention.'} onRetry={onRetry}/>}</section><aside className="log-card"><div><h3>Live activity</h3><span className={job.status === 'processing' ? 'live-dot' : 'muted'}>{job.status === 'processing' ? 'Live' : job.status}</span></div><div className="logs" aria-live="polite">{job.logs.length ? job.logs.slice(-10).map((line, index) => <p key={`${index}-${line}`}><span>›</span>{line}</p>) : <p>Preparing your project. Activity will appear here.</p>}</div><Button variant="secondary" disabled={job.status !== 'processing'} onClick={cancel}>Cancel processing</Button></aside></div></PageShell>;
}

function Review({ jobs, setPage }: { jobs: Job[]; setPage: (page: Page) => void }) {
  const job = jobs.find(item => item.status === 'completed' && item.result?.highlights?.length) ?? jobs.find(item => item.status === 'completed'); const highlights = job?.result?.highlights ?? []; const [selected, setSelected] = useState<number[]>([]);
  useEffect(() => { setSelected(highlights.map((_, index) => index)); }, [job?.id, highlights.length]);
  if (!job || !highlights.length) return <PageShell eyebrow="Review" title="Choose your best moments"><p className="page-description">AI-ranked candidates, ready for your creative direction.</p><EmptyState icon={Layers3} title="No highlights ready for review" description="Run a project in review mode to choose exactly which moments to render." action="Generate a project" onAction={() => setPage('generate')}/></PageShell>;
  return <PageShell eyebrow="Review" title="Choose your best moments" action={<Button disabled={!selected.length}>Render {selected.length} selected <Sparkles size={16}/></Button>}><p className="page-description">AI-ranked candidates from <b>{titleFromFile(job.filename)}</b>. You stay in control of the final cut.</p><div className="review-summary"><span className="thumb large"><Play size={23}/></span><div><b>{job.filename}</b><span>{highlights.length} highlights detected · Ranked by gameplay intelligence</span></div><div className="summary-score"><b>{Math.round(highlights.reduce((sum, item) => sum + (item.overall_score ?? item.score ?? 0), 0) / highlights.length)}</b><span>Avg. score</span></div></div><div className="highlight-grid">{highlights.map((highlight, index) => { const score = highlight.overall_score ?? highlight.score ?? 0; const checked = selected.includes(index); return <article className={`highlight-card ${checked ? 'checked' : ''}`} key={`${highlight.start_time}-${index}`}><button type="button" className="check" aria-label={`${checked ? 'Remove' : 'Add'} highlight ${index + 1}`} aria-pressed={checked} onClick={() => setSelected(current => checked ? current.filter(item => item !== index) : [...current, index])}>{checked ? '✓' : ''}</button><div className="highlight-preview"><Play size={21}/><span>{formatSeconds(highlight.start_time)} – {formatSeconds(highlight.end_time)}</span></div><div className="highlight-content"><div><span className="rank">#{index + 1} highlight</span><b className="score">{score}<small>/100</small></b></div><h3>{highlight.hook_sentence || 'A moment worth replaying'}</h3><p>{highlight.reason_selected || highlight.virality_reason || 'Strong gameplay moment identified by the AI.'}</p><div className="score-bars">{[['Gameplay', highlight.gameplay_score], ['Emotion', highlight.emotion_score], ['Action', highlight.action_score]].map(([label, value]) => <span key={String(label)}>{label}<i><b style={{ width: `${Number(value ?? score)}%` }}/></i></span>)}</div></div></article>; })}</div></PageShell>;
}

function ProjectsTable({ type, jobs, isLoading, setPage }: { type: 'history' | 'projects'; jobs: Job[]; isLoading: boolean; setPage: (page: Page) => void }) {
  const [search, setSearch] = useState(''); const [latest, setLatest] = useState(true); const filtered = useMemo(() => jobs.filter(job => titleFromFile(job.filename).toLowerCase().includes(search.toLowerCase())).sort((a, b) => latest ? b.created_at.localeCompare(a.created_at) : a.created_at.localeCompare(b.created_at)), [jobs, search, latest]);
  const isHistory = type === 'history'; return <PageShell eyebrow={isHistory ? 'Archive' : 'Workspace'} title={isHistory ? 'Processing history' : 'Projects'} action={!isHistory ? <Button onClick={() => setPage('generate')}><Plus size={17}/>New project</Button> : undefined}><p className="page-description">{isHistory ? 'A complete record of your local AI processing activity.' : 'Every upload is saved as a project, ready to revisit.'}</p><div className="toolbar"><label className="search"><Search size={17}/><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search projects" aria-label="Search projects"/></label><Button variant="secondary" onClick={() => setLatest(value => !value)}>{latest ? 'Latest first' : 'Oldest first'}</Button></div><section className="table-card"><div className="table-head"><span>PROJECT</span><span>STATUS</span><span>CLIPS</span><span>CREATED</span><span/></div>{isLoading ? <LoadingRows/> : filtered.length ? filtered.map(job => <ProjectRow key={job.id} job={job} onOpen={() => setPage(job.status === 'completed' ? 'review' : 'history')}/>) : <EmptyState icon={isHistory ? Clock3 : FolderKanban} title={search ? 'No matching projects' : isHistory ? 'No processing history yet' : 'No projects yet'} description={search ? 'Try another project name or clear your search.' : isHistory ? 'Your uploads and processing runs will be recorded here.' : 'Create a project to save a gameplay session and its clips.'} action={search ? 'Clear search' : 'Create a project'} onAction={() => search ? setSearch('') : setPage('generate')}/>}</section></PageShell>;
}

function Analytics({ jobs }: { jobs: Job[] }) { const completed = jobs.filter(job => job.status === 'completed'); return <PageShell eyebrow="Insights" title="Your creative performance"><p className="page-description">See how your AI editing workflow is performing over time.</p><div className="analytics-grid"><section className="chart-card wide"><div><h3>Clips created</h3><p>{completed.length ? 'Last 6 weeks' : 'Your activity will appear here'}</p></div>{completed.length ? <div className="bar-chart">{[18, 38, 28, 61, 44, 78, 56, 88, 68, 92, 71, 82].map((height, index) => <i key={index} style={{ height: `${height}%` }}/>)}</div> : <div className="chart-empty">Create your first project to start building creative insights.</div>}</section><section className="chart-card"><h3>Top game profiles</h3><div className="donut"><b>{completed.length}</b><span>projects</span></div><p className="muted">Profile data builds as projects complete.</p></section><section className="chart-card"><h3>Average AI score</h3><strong className="big-number">{completed.length ? '87.4' : '—'}</strong><span className="positive">{completed.length ? '+4.8% this month' : 'Complete projects to compare scores'}</span></section><section className="chart-card"><h3>Rendering usage</h3><strong className="big-number">{completed.reduce((total, job) => total + (job.result?.shorts?.length ?? 0), 0)}</strong><span className="muted">clips this month</span></section></div></PageShell>; }

function SettingsPage() { const [gpu, setGpu] = useState(true); return <PageShell eyebrow="Workspace" title="Settings"><div className="settings-layout"><aside aria-label="Settings sections"><button className="active" type="button">General</button><button type="button">Processing</button><button type="button">Integrations</button><button type="button">Storage</button><button type="button">Advanced</button></aside><section className="settings-panel"><h2>General preferences</h2><p>Set defaults for every new project. They can always be changed before processing.</p><label>Default game profile<select defaultValue="auto"><option value="auto">Auto-detect</option><option>The Last of Us</option><option>GTA VI</option></select></label><label>Default layout<select defaultValue="adaptive"><option value="adaptive">Adaptive</option><option>Single focus</option></select></label><div className="switch-row"><div><b>Hardware acceleration</b><span>Use the GPU when supported by local processing tools.</span></div><button type="button" className={`switch ${gpu ? 'on' : ''}`} role="switch" aria-checked={gpu} aria-label="Hardware acceleration" onClick={() => setGpu(value => !value)}><i/></button></div><hr/><h3>API configuration</h3><p className="muted">Keys are stored only in your local environment; they are never exposed in this interface.</p><Button variant="secondary">Open local configuration</Button></section></div></PageShell>; }

function Help() { const cards = [['Get started', 'Learn the workflow from upload to export.'], ['Processing guides', 'Make the most of game profiles and scoring.'], ['Troubleshooting', 'Diagnose local engine and render issues.']]; return <PageShell eyebrow="Support" title="How can we help?"><p className="page-description">Clear, local-first guidance for every stage of your workflow.</p><div className="help-grid">{cards.map(([title, copy]) => <button className="help-card" type="button" key={title}><span className="icon-box"><HelpCircle size={20}/></span><h3>{title}</h3><p>{copy}</p><ChevronRight size={17}/></button>)}</div></PageShell>; }

function App() {
  const [page, setPage] = useState<Page>('dashboard'); const [activeJob, setActiveJob] = useState<Job>(); const { data: jobs = [], isError, isLoading, refetch } = useJobs(); const liveJob = activeJob ? jobs.find(job => job.id === activeJob.id) ?? activeJob : undefined;
  const showReview = useCallback(() => { setActiveJob(undefined); setPage('review'); }, []);
  const content = liveJob && ['queued', 'processing', 'failed'].includes(liveJob.status) ? <Processing job={liveJob} onComplete={showReview} onRetry={() => setPage('generate')}/> : (() => { switch (page) { case 'dashboard': return <Dashboard jobs={jobs} isLoading={isLoading} setPage={setPage}/>; case 'generate': return <Generate onJob={job => setActiveJob(job)}/>; case 'review': return <Review jobs={jobs} setPage={setPage}/>; case 'history': return <ProjectsTable type="history" jobs={jobs} isLoading={isLoading} setPage={setPage}/>; case 'projects': return <ProjectsTable type="projects" jobs={jobs} isLoading={isLoading} setPage={setPage}/>; case 'analytics': return <Analytics jobs={jobs}/>; case 'settings': return <SettingsPage/>; default: return <Help/>; } })();
  return <div className="app"><Sidebar page={page} setPage={setPage}/><div className="content">{isError && <div className="api-warning" role="alert"><b>Local service is offline.</b><span>Start the API, then reconnect.</span><Button variant="secondary" onClick={() => refetch()}><RefreshCw size={14}/>Reconnect</Button></div>}{content}</div></div>;
}

createRoot(document.getElementById('root')!).render(<StrictMode><QueryClientProvider client={queryClient}><App/></QueryClientProvider></StrictMode>);
