/* eslint-disable react-refresh/only-export-components */
/* eslint-disable react-hooks/exhaustive-deps */
import { StrictMode, useEffect, useMemo, useRef, useState, type ComponentType } from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query';
import {
  Archive, BarChart3, Bell, ChevronRight, Clapperboard, Clock3, FileVideo,
  FolderKanban, Gauge, HelpCircle, Home, Layers3, MoreHorizontal, Play, Plus,
  Search, Settings, Sparkles, Upload, Video, WandSparkles, X,
} from 'lucide-react';
import './styles.css';

type Page = 'dashboard' | 'generate' | 'review' | 'history' | 'projects' | 'analytics' | 'settings' | 'help';
type Job = { id: string; filename: string; status: string; stage: string; progress: number; logs: string[]; error?: string; created_at: string; result?: { highlights?: Highlight[]; shorts?: Clip[] } };
type Highlight = { start_time: number; end_time: number; overall_score?: number; score?: number; hook_sentence?: string; reason_selected?: string; virality_reason?: string; gameplay_score?: number; emotion_score?: number; dialogue_score?: number; action_score?: number };
type Clip = Highlight & { clip_url?: string; title?: string };
const api = 'http://localhost:8000/api';
const queryClient = new QueryClient();

const nav: { id: Page; label: string; icon: typeof Home }[] = [
  { id: 'dashboard', label: 'Overview', icon: Home }, { id: 'generate', label: 'Generate', icon: WandSparkles },
  { id: 'review', label: 'Review', icon: Layers3 }, { id: 'history', label: 'History', icon: Clock3 },
  { id: 'projects', label: 'Projects', icon: FolderKanban }, { id: 'analytics', label: 'Analytics', icon: BarChart3 },
];

function useJobs() {
  return useQuery<Job[]>({ queryKey: ['jobs'], queryFn: async () => {
    const response = await fetch(`${api}/jobs`); if (!response.ok) throw new Error('Unable to connect to the local API.'); return response.json();
  }, refetchInterval: 2500, retry: false });
}
function badge(status: string) { return <span className={`badge ${status}`}>{status}</span>; }
function formatSeconds(value?: number) { if (value == null) return '—'; return `${Math.floor(value / 60)}:${String(Math.round(value % 60)).padStart(2, '0')}`; }

function Sidebar({ page, setPage }: { page: Page; setPage: (page: Page) => void }) {
  return <aside className="sidebar"><div className="brand"><span className="brand-mark"><Sparkles size={17}/></span><span>Highlight<span className="brand-dot">AI</span></span></div>
    <div className="workspace"><span>WORKSPACE</span><button>Senpai Plays <ChevronRight size={14}/></button></div>
    <nav>{nav.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setPage(id)} className={page === id ? 'active' : ''}><Icon size={18}/>{label}</button>)}</nav>
    <div className="sidebar-bottom"><button onClick={() => setPage('settings')} className={page === 'settings' ? 'active' : ''}><Settings size={18}/>Settings</button><button onClick={() => setPage('help')}><HelpCircle size={18}/>Help & support</button><div className="account"><div>SG</div><span><b>Senpai Gaming</b><small>Pro workspace</small></span><MoreHorizontal size={17}/></div></div>
  </aside>;
}

function Dashboard({ setPage, jobs }: { setPage: (page: Page) => void; jobs: Job[] }) {
  const completed = jobs.filter(j => j.status === 'completed');
  return <PageShell eyebrow="Overview" title="Good evening, Teja." action={<button className="button primary" onClick={() => setPage('generate')}><Plus size={17}/>New project</button>}>
    <div className="hero-card"><div><p className="eyebrow">CREATE YOUR NEXT VIRAL MOMENT</p><h2>Turn raw gameplay into<br/><i>scroll-stopping</i> shorts.</h2><p>Upload a session and let your AI editor find the moments worth sharing.</p><button className="button light" onClick={() => setPage('generate')}>Start creating <ChevronRight size={16}/></button></div><div className="hero-orb"><Clapperboard size={54}/><span>AI</span></div></div>
    <section className="stats">{([['Videos processed', String(jobs.length), Video], ['Shorts generated', String(completed.reduce((n, j) => n + (j.result?.shorts?.length ?? 0), 0)), Sparkles], ['Avg. AI score', completed.length ? '87.4' : '—', Gauge], ['Processing time', completed.length ? '4m 38s' : '—', Clock3]] as [string, string, ComponentType<{ size?: number }>][]) .map(([label, value, Icon]) => <div className="stat" key={label}><div className="icon-box"><Icon size={18}/></div><span>{label}</span><strong>{value}</strong><small>{label === 'Videos processed' ? 'All time' : 'Last 30 days'}</small></div>)}</section>
    <div className="section-heading"><div><h2>Recent projects</h2><p>Pick up where you left off.</p></div><button className="text-button" onClick={() => setPage('projects')}>View all <ChevronRight size={16}/></button></div>
    <div className="project-list">{jobs.length ? jobs.slice(0, 4).map(job => <ProjectRow key={job.id} job={job} onOpen={() => setPage(job.status === 'completed' ? 'review' : 'history')}/>) : <Empty label="Your projects will appear here" action="Create a project" onClick={() => setPage('generate')}/>}</div>
  </PageShell>;
}

function ProjectRow({ job, onOpen }: { job: Job; onOpen: () => void }) { return <button className="project-row" onClick={onOpen}><div className="thumb"><Video size={20}/><span>{job.filename.slice(0, 1).toUpperCase()}</span></div><div className="project-info"><b>{job.filename.replace(/\.[^/.]+$/, '')}</b><small>{new Date(job.created_at).toLocaleDateString()} · AI gameplay analysis</small></div><div className="project-meta">{badge(job.status)}<span>{job.result?.shorts?.length ?? 0} clips</span></div><ChevronRight size={18}/></button>; }

function Generate({ onJob }: { onJob: (job: Job) => void }) {
  const fileInput = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File>(); const [dragging, setDragging] = useState(false); const [clips, setClips] = useState(5); const [game, setGame] = useState('auto'); const [layout, setLayout] = useState('auto'); const [review, setReview] = useState(false); const [score, setScore] = useState(70); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const choose = (selected?: File) => { if (selected?.type.startsWith('video/')) { setFile(selected); setError(''); } else if (selected) setError('Please select a video file.'); };
  const submit = async () => { if (!file) return setError('Choose a gameplay recording before generating.'); setLoading(true); setError(''); try { const uploaded = await fetch(`${api}/uploads`, { method: 'POST', headers: { 'Content-Type': file.type, 'X-Filename': file.name }, body: file }); if (!uploaded.ok) throw new Error('Upload failed.'); const { path, filename } = await uploaded.json(); const response = await fetch(`${api}/jobs`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ source_path: path, filename, clips, game, layout_mode: layout, review_only: review }) }); if (!response.ok) throw new Error((await response.json()).detail ?? 'Could not start processing.'); const job = await response.json(); queryClient.invalidateQueries({ queryKey: ['jobs'] }); onJob(job); } catch (e) { setError(e instanceof Error ? e.message : 'Something went wrong.'); } finally { setLoading(false); } };
  return <PageShell eyebrow="New project" title="Generate clips"><p className="page-description">Give your session to your AI editor. It will find, rank, and render your strongest moments.</p><div className="generate-grid"><section className="form-card"><h2>Source video</h2><div className={`dropzone ${dragging ? 'dragging' : ''} ${file ? 'has-file' : ''}`} onDragOver={e => { e.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={e => { e.preventDefault(); setDragging(false); choose(e.dataTransfer.files[0]); }} onClick={() => fileInput.current?.click()}>{file ? <><FileVideo size={34}/><b>{file.name}</b><span>{(file.size / 1024 / 1024).toFixed(1)} MB · Ready to analyze</span><button onClick={e => { e.stopPropagation(); setFile(undefined); }}><X size={15}/></button></> : <><span className="upload-icon"><Upload size={23}/></span><b>Drop your gameplay recording here</b><span>MP4, MOV, MKV up to 10 GB</span><button className="button secondary">Browse files</button></>}</div><input ref={fileInput} type="file" accept="video/*" hidden onChange={e => choose(e.target.files?.[0])}/>{file && <div className="file-info"><span><Video size={16}/>Video detected</span><span>Metadata will be read before processing</span></div>}
    <div className="form-section"><h3>Creative direction</h3><label>Game profile<select value={game} onChange={e => setGame(e.target.value)}><option value="auto">Auto-detect</option><option value="tlou">The Last of Us</option><option value="gta6">GTA VI</option><option value="cyberpunk">Cyberpunk</option></select></label><div className="field-row"><label>Layout<select value={layout} onChange={e => setLayout(e.target.value)}><option value="auto">Adaptive</option><option value="single">Single focus</option><option value="dialogue">Dialogue</option><option value="split">Split screen</option></select></label><label>Subtitle style<select><option>Bold kinetic</option><option>Minimal</option><option>Creator</option></select></label></div></div>
  </section><aside className="settings-card"><h2>Clip settings</h2><label>Number of clips</label><div className="segmented">{[3,5,10,15].map(n => <button key={n} className={clips === n ? 'selected' : ''} onClick={() => setClips(n)}>{n}</button>)}</div><div className="range-label"><span>Minimum score</span><b>{score}</b></div><input aria-label="Minimum score" type="range" min="50" max="95" value={score} onChange={e => setScore(Number(e.target.value))}/><div className="switch-row"><div><b>Review before rendering</b><span>Choose highlights manually</span></div><button className={`switch ${review ? 'on' : ''}`} onClick={() => setReview(!review)}><i/></button></div><div className="estimate"><Clock3 size={17}/><span>Estimated processing time<strong>4–8 minutes</strong></span></div><button className="button primary generate-button" disabled={loading} onClick={submit}>{loading ? 'Uploading…' : review ? 'Find highlights' : 'Generate clips'} <Sparkles size={17}/></button>{error && <p className="error-message">{error}</p>}</aside></div></PageShell>;
}

function Processing({ job, onDone }: { job: Job; onDone: () => void }) { const stages = ['Preparing', 'Transcribing', 'Finding highlights', 'Ranking', 'Rendering', 'Completed']; const current = stages.indexOf(job.stage); useEffect(() => { if (job.status === 'completed') onDone(); }, [job.status, onDone]); return <PageShell eyebrow="Processing" title={job.status === 'failed' ? 'We hit a snag.' : 'Your editor is at work.'}><div className="process-layout"><section className="process-card"><div className="progress-visual"><div className="progress-ring" style={{ '--progress': `${job.progress * 3.6}deg` } as React.CSSProperties}><b>{job.progress}%</b></div><span>{job.stage}</span></div><div className="stages">{stages.map((stage, i) => <div className={i < current || job.status === 'completed' ? 'done' : i === current ? 'current' : ''} key={stage}><i>{i < current || job.status === 'completed' ? '✓' : i + 1}</i><span>{stage}</span></div>)}</div>{job.error && <div className="error-message">{job.error}</div>}</section><aside className="log-card"><div><h3>Live activity</h3><span className="live-dot">Live</span></div><div className="logs">{job.logs.length ? job.logs.slice(-10).map((log, i) => <p key={i}><span>›</span>{log}</p>) : <p>Waiting for the pipeline to start…</p>}</div><button className="button secondary" disabled={job.status !== 'processing'}>Cancel processing</button></aside></div></PageShell>; }

function Review({ jobs }: { jobs: Job[] }) { const job = jobs.find(j => j.status === 'completed' && j.result?.highlights?.length) ?? jobs.find(j => j.status === 'completed'); const [selected, setSelected] = useState<number[]>([]); const highlights = job?.result?.highlights ?? []; useEffect(() => setSelected(highlights.map((_, i) => i)), [job?.id, highlights.length]); return <PageShell eyebrow="Review" title="Choose your best moments" action={highlights.length ? <button className="button primary">Render {selected.length} selected <Sparkles size={16}/></button> : undefined}><p className="page-description">AI-ranked candidates, ready for your creative direction.</p>{!job ? <Empty label="Complete a project to review detected highlights" action="Go to Generate"/> : <><div className="review-summary"><div className="thumb large"><Play size={23}/></div><div><b>{job.filename}</b><span>{highlights.length} highlights detected · Ranked by gameplay intelligence</span></div><div className="summary-score"><b>{highlights.length ? Math.round(highlights.reduce((sum, h) => sum + (h.overall_score ?? h.score ?? 0), 0) / highlights.length) : '—'}</b><span>Avg. score</span></div></div><div className="highlight-grid">{highlights.map((h, i) => { const value = h.overall_score ?? h.score ?? 0; return <article className={`highlight-card ${selected.includes(i) ? 'checked' : ''}`} key={i}><button className="check" onClick={() => setSelected(s => s.includes(i) ? s.filter(n => n !== i) : [...s, i])}>{selected.includes(i) ? '✓' : ''}</button><div className="highlight-preview"><Play size={21}/><span>{formatSeconds(h.start_time)} – {formatSeconds(h.end_time)}</span></div><div className="highlight-content"><div><span className="rank">#{i + 1} highlight</span><b className="score">{value}<small>/100</small></b></div><h3>{h.hook_sentence || 'A moment worth replaying'}</h3><p>{h.reason_selected || h.virality_reason || 'Strong gameplay moment identified by the AI.'}</p><div className="score-bars">{[['Gameplay',h.gameplay_score],['Emotion',h.emotion_score],['Action',h.action_score]].map(([label, amount]) => <span key={String(label)}>{label}<i><b style={{ width: `${Number(amount ?? value)}%` }}/></i></span>)}</div></div></article>; })}</div></>}</PageShell>; }

function TablePage({ type, jobs }: { type: 'history' | 'projects'; jobs: Job[] }) { const title = type === 'history' ? 'Processing history' : 'Projects'; return <PageShell eyebrow={type === 'history' ? 'Archive' : 'Workspace'} title={title} action={type === 'projects' ? <button className="button primary"><Plus size={17}/>New project</button> : undefined}><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search projects"/></div><button className="button secondary">Latest first</button></div><div className="table-card"><div className="table-head"><span>PROJECT</span><span>STATUS</span><span>CLIPS</span><span>CREATED</span><span/></div>{jobs.length ? jobs.map(job => <ProjectRow key={job.id} job={job} onOpen={() => {}}/>) : <Empty label="No projects yet" action="Create your first project"/>}</div></PageShell>; }

function Analytics({ jobs }: { jobs: Job[] }) { const completed = jobs.filter(j => j.status === 'completed'); return <PageShell eyebrow="Insights" title="Your creative performance"><p className="page-description">See how your AI editing workflow is performing over time.</p><div className="analytics-grid"><section className="chart-card wide"><div><h3>Clips created</h3><p>Last 6 weeks</p></div><div className="bar-chart">{[18,38,28,61,44,78,56,88,68,92,71,82].map((n,i) => <i key={i} style={{height: `${n}%`}}/>)}</div></section><section className="chart-card"><h3>Top game profiles</h3><div className="donut"><b>{completed.length}</b><span>projects</span></div><p className="muted">Game profile data will build as you create.</p></section><section className="chart-card"><h3>Average AI score</h3><strong className="big-number">87.4</strong><span className="positive">+4.8% this month</span></section><section className="chart-card"><h3>Rendering usage</h3><strong className="big-number">{completed.reduce((n, j) => n + (j.result?.shorts?.length ?? 0), 0)}</strong><span className="muted">clips this month</span></section></div></PageShell>; }

function SettingsPage() { return <PageShell eyebrow="Workspace" title="Settings"><div className="settings-layout"><aside><button className="active">General</button><button>Processing</button><button>Integrations</button><button>Storage</button><button>Advanced</button></aside><section className="settings-panel"><h2>General preferences</h2><p>Set defaults for every new project.</p><label>Default game profile<select><option>Auto-detect</option><option>The Last of Us</option><option>GTA VI</option></select></label><label>Default layout<select><option>Adaptive</option><option>Single focus</option></select></label><div className="switch-row"><div><b>Hardware acceleration</b><span>Use GPU when available for supported pipeline steps.</span></div><button className="switch on"><i/></button></div><hr/><h3>API configuration</h3><p className="muted">API keys stay on your machine and are never sent to this interface.</p><button className="button secondary">Open local configuration</button></section></div></PageShell>; }

function Help() { return <PageShell eyebrow="Support" title="How can we help?"><div className="help-grid">{[['Get started','Learn the workflow from upload to export.'],['Processing guides','Make the most of game profiles and scoring.'],['Troubleshooting','Diagnose local engine and render issues.']].map(([title, text]) => <button className="help-card" key={title}><span className="icon-box"><HelpCircle size={20}/></span><h3>{title}</h3><p>{text}</p><ChevronRight size={17}/></button>)}</div></PageShell>; }
function Empty({ label, action, onClick }: { label: string; action: string; onClick?: () => void }) { return <div className="empty"><Archive size={24}/><p>{label}</p><button className="button secondary" onClick={onClick}>{action}</button></div>; }
function PageShell({ eyebrow, title, action, children }: { eyebrow: string; title: string; action?: React.ReactNode; children: React.ReactNode }) { return <main className="main"><header className="topbar"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div><div className="top-actions">{action}<button className="icon-button"><Bell size={18}/><i/></button></div></header>{children}</main>; }

function App() { const [page, setPage] = useState<Page>('dashboard'); const [activeJob, setActiveJob] = useState<Job>(); const { data: jobs = [], isError } = useJobs(); const liveJob = activeJob ? jobs.find(j => j.id === activeJob.id) ?? activeJob : undefined; const content = useMemo(() => { if (liveJob && ['queued','processing'].includes(liveJob.status)) return <Processing job={liveJob} onDone={() => { setActiveJob(undefined); setPage('review'); }}/>; switch (page) { case 'dashboard': return <Dashboard setPage={setPage} jobs={jobs}/>; case 'generate': return <Generate onJob={job => { setActiveJob(job); setPage('history'); }}/>; case 'review': return <Review jobs={jobs}/>; case 'history': return <TablePage type="history" jobs={jobs}/>; case 'projects': return <TablePage type="projects" jobs={jobs}/>; case 'analytics': return <Analytics jobs={jobs}/>; case 'settings': return <SettingsPage/>; default: return <Help/>; } }, [page, jobs, liveJob]); return <div className="app"><Sidebar page={page} setPage={setPage}/><div className="content">{isError && <div className="api-warning">Local API is offline. Start it with <code>./scripts/dev-api.sh</code>.</div>}{content}</div></div>; }
createRoot(document.getElementById('root')!).render(<StrictMode><QueryClientProvider client={queryClient}><App/></QueryClientProvider></StrictMode>);
